### PR TITLE
Add Semigroup/Monoid instance of Dictionary

### PR DESCRIPTION
**Pull request by stephencelis**
From https://github.com/pointfreeco/pointfreeco-server/blob/1074281c9a3dc9d3230871a6ed053e14458efbbb/Sources/pointfreeco/main.swift#L38

Dictionary's a strange one because, when you have conditional conformance, would you want to also support this?

``` swift
extension Dictionary: Semigroup where Value: Semigroup {
  public static func <>(lhs: Dictionary, rhs: Dictionary) -> Dictionary {
    return lhs.merging(rhs, uniquingKeysWith: <>)
  }
}
```

Maybe both will work just fine in the end?

### CODE REVIEW

**Comment by mbrandonw** [comment]
> Dictionary's a strange one because, when you have conditional conformance, would you want to also support this?

dictionary has all types of monoid instances, like you could unique with left or right keys... 🤔

**Comment by mbrandonw** [comment]
> Maybe both will work just fine in the end?

I think those overlapping conformances wouldn't be allowed?

**Comment by stephencelis** [comment]
The Monoid instance that makes the most sense is to favor the righthand side, no? (Even in Ruby, `merge` is built-in, but `reverse_merge` is a lesser-used sugar from Active Support.)

Then again, purescript-maps prefers the first:

https://github.com/purescript/purescript-maps/blob/master/src/Data/Map.purs#L562-L576

Maybe we just make helpers with better names for preferring first and second?

**Comment by mbrandonw** [comment]
I forget where I saw this, but favoring the right-side can be seen as a security risk in which you unknowingly overwrite defaults given by a framework. I think this is the main reason the swift stdlib team agonized over what to call merge and came up with that `uniquingKeysWith` name.

**Comment by stephencelis** [comment]
Closing this! I ended up adding an operator on env vars instead.

**Pull request closed without merging**
