### PR TITLE
Add support for CocoaPods

### PR DESCRIPTION
**Pull request by Killectro**
I think there are a few things that need to be done before this is ready to go:

- [ ] Add a new 0.1.3 (or whatever) release
- [ ] Update `.podspec` to point to that release
- [ ] Verify that emails are correct in the `.podspec` (I guessed)
- [ ] Verify that deployment targets are correct
- [ ] Run `pod spec lint` to make sure it can be built with the latest code
- [ ] Upload spec to trunk (here is a [helpful guide](https://guides.cocoapods.org/making/getting-setup-with-trunk.html))

### CODE REVIEW

**Comment by Killectro** [comment]
I just did some more digging and it's actually not as simple as this. Because the project is structured to treat the individual local libs as separate targets I think this might not compile when someone tries to pull this in as a dependency. Given my general lack of experience maintaining pods I'm not 100% sure how to replicate what you're doing in `Package.swift` inside of a `.podspec`, but I don't think something this simple will do it.

**Comment by stephencelis** [comment]
Hey DJ! Sorry for not being more responsive! It's been a busy week. We're very interested in figuring out these kinds of dependency situations in general, but we've had trouble ensuring that CocoaPods and Carthage work in the longterm for most of the open source projects we've worked on. Lemme talk to @mbrandonw about how we can try to ensure that libraries we work on, even experimental ones like the Prelude, can have support for CocoaPods and other dependency management systems.

**Comment by stephencelis** [comment]
Another update :) We got around to figuring out XcodeGen for a repo to battle some SwiftPM weirdness and to unlock Carthage support: https://github.com/pointfreeco/swift-snapshot-testing/pull/77

We'll be wanting to further explore how we can use this approach in _all_ our repos. Hopefully soon!

**Comment by stephencelis** [comment]
From #107: 😅

> And the world turns :) We've been slowly phasing out support for non-SPM tools, and Prelude's been in a bit of a "maintenance mode," so we're going to finally close this out. Thanks for coming along on the journey 😄

**Pull request closed without merging**
