### PR TITLE
Add support for Carthage

### PR DESCRIPTION
**Pull request by mluisbrown**
This adds support for installing the Prelude frameworks using Carthage.

Basically:
* remove the gitignore for `.xcodeproj` files
* use the `Prelude.xcodeproj` file generated by `make xcodeproj` as a starting point, removing the `Diff`, `SnapshotTesting` and `WKSnapshotConfigurationShim` targets from the Run and Archive builds as they are incompatible with arm64 builds and aren't required when building as a dependency.
* Add `swift-tagged` as a Carthage dependency (at version `0.2.0`) using submodules (`carthage checkout --use-submodules)` and include the `Tagged` project into the `Prelude` workspace.
* Delete the SPM created `Tagged` dependency from the `Prelude` project and use the framework built from the `Tagged` sub-project as the dependency for `Prelude`.

`make xcodeproj` will overwrite `Prelude.xcodeproj` so this doesn't affect building and testing using SPM.

### CODE REVIEW

**Comment by mbrandonw** [comment]
@mluisbrown hey thanks for this and sorry for the radio silence! we're interested in doing this (and the same with some of our other packages), but we need a bit more time to figure out a sustainable way to do this. so far we've been having a bit of pain supporting Carthage.

Thanks again!

**Comment by mluisbrown** [comment]
Thanks for letting me know @mbrandonw. What are the issues with Carthage that you are facing? At work we are looking to include Prelude into one of our frameworks and we would really need Carthage support for this.

**Comment by sloik** [comment]
What about cocoapods? :)

**Comment by stephencelis** [comment]
Hey @mluisbrown (and @sloik)! It's been awhile but we've been exploring this more recently and have an update here: 
https://github.com/pointfreeco/swift-prelude/pull/113#issuecomment-436845829

**Comment by stephencelis** [comment]
And the world turns :) We've been slowly phasing out support for non-SPM tools, and Prelude's been in a bit of a "maintenance mode," so we're going to finally close this out. Thanks for coming along on the journey 😄

**Pull request closed without merging**
